### ISSUE TITLE
Bugs on dxLabel & dxCheckBox

### ISSUE THREAD

**Issue by pashabeys** [clawsuit/dxLibrary#2]
There are a few bugs at dxLabel & dxCheckBox. I can't create.

**Comment by clawsuit** [comment]
bad use of syntax?

**Comment by pashabeys** [comment]
I don't think so, I can't create label at center of window.

**Comment by pashabeys** [comment]
I think, I found the error, If I set x >= 1000 or y >= 50, fps is being 10.

**Comment by clawsuit** [comment]
If there was any error then it was fixed

**Comment by clawsuit** [comment]
By the way, in the labels the W,H (base) coordinates cannot exceed the X,Y

For example, some base coordinates of a rectangle would be

x,y,w,h = 100, 50, 40, 30

If we create a label to that rectangle the calculation would be

dxLabel(x,y,w+x, y+h, '')

inside the label a brief subtraction is made, that is why the W,H should never be greater than the X,Y, since the drawing box throws an error and generates lags due to negative sizes
